server:
  port: 9900
spring:
  data:
    mongodb:
      uri: mongodb://localhost/seckilldemo
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-idle: 5
        max-wait: 1s
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest